%global tl_name tree-dvips
%global tl_revision 21751

Name:		texlive-%{tl_name}
Epoch:		1
Version:	91
Release:	%{tl_revision}.1
Summary:	Trees and other linguists macros
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/latex209/contrib/trees/tree-dvips
License:	lppl1
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/tree-dvips.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/tree-dvips.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
The package defines a mechanism for specifying connected trees that uses
a tabular environment to generate node positions. The package uses
PostScript code, loaded by dvips, so output can only be generated by use
of dvips. The package lingmacros.sty defines a few macros for linguists:
\enumsentence for enumerating sentence examples, simple tabular-based
non-connected tree macros, and gloss macros.

